### ISSUE TITLE
Download not found

### ISSUE THREAD

**Issue by LarryBetz** [Vito0912/abs_flutter#86] opened 2024-11-12 17:17 UTC
On a new installation, downloaded my first book. Listen to it for an hour. Close the application, came back later and the book was not in the continue listening category. Search for the book when I clicked on it I received an error not found

![Screenshot_20241112_091232](https://github.com/user-attachments/assets/f3b752ce-f6b9-4bfc-962b-168208cc8cad)

**Comment by Vito0912** [comment] 2024-11-12 17:17
duplicate of #82

**Closed by Vito0912** 2024-11-12 17:17 UTC
